// client/src/routes/register.svelte
<script context="module">
	export function preload(_page, session) {
		if (session.loggedIn) this.redirect(303, '/')
	}
</script>

<script lang="ts">
	import axios from 'axios'
	import FancyInput from '../components/FancyInput.svelte'
	import FancyButton from '../components/FancyButton.svelte'
	import FormErrorMessage from '../components/FormErrorMessage.svelte'

	/** true se o usuário completou o cadastro */
	let registered = false
	let email: string
	let errorMessage = ''

	async function handleSubmit(event) {
		email = event.target.email.value
		const password = event.target.password.value
		if (password != event.target.conf_password.value)
			return errorMessage = 'Password and confirmation pasword do not match'

		try {
			await axios.post(window.location.href, { email, password })
			registered = true
		} catch(err) {
			if (err.response?.status === 409) {
				errorMessage = 'Já existe um usuário cadastrado com o e-mail informado'
			} else {
				errorMessage = err.response?.statusText || err.message
			}
		}
	}
</script>

<style>
	h1, div {
		margin-top: 0.5em;
	}

	h1, h2, p {
		text-align: center;
	}

	form, div {
		width: 350px;
		height: 100%;
		border: 1px solid lightgray;
		margin-top: 1.5em;
		margin-left: auto;
		margin-right: auto;
		padding: 20px;
		border-radius: 6px;
		box-shadow: 0px 5px 50px 0px rgba(18, 89, 93, 0.15);
		line-height: 50px;
	}

	div {
		width: 400px;
	}
</style>

{#if registered}
	<div>
		<h2>Confirme o email</h2>
		<p>
			Enviamos um email de confirmação de cadastro para <b>{email}</b>, para ativar sua conta por favor siga as instruções informadas no email
		</p>
		<!-- função ainda precisa ser implementada -->
		<FancyButton>Confirmar e-mail</FancyButton>
	</div>
{:else}
	<h1>Register</h1>
	<form on:submit|preventDefault={handleSubmit}>
		{#if errorMessage}
			<FormErrorMessage>{errorMessage}</FormErrorMessage>
		{/if}
		<FancyInput id="email" type="email">Email</FancyInput>
		<FancyInput id="password" type="password">Password</FancyInput>
		<FancyInput id="conf_password" type="password">Confirm password</FancyInput>

		<FancyButton type="submit">Register</FancyButton>
	</form>
{/if}

// client/src/pages/register/Register.jsx
import React from 'react';
import axios from 'axios';

import './Register.css';
import InputField from "../../components/InputField/InputField";
import RoundButton from "../../components/RoundButton/RoundButton";
import ErrorMessage from "../../components/ErrorMessage/ErrorMessage";

export default class Register extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            email: '',
            password: '',
            emailConfirm: false,
            errorMsg: ''
        };
        this.handleChange = this.handleChange.bind(this);
        this.handleSubmit = this.handleSubmit.bind(this);
    };

    handleChange = (e) => {
        this.setState({
            [e.target.name]: e.target.value
        });
    };

    handleSubmit = (e) => {
        e.preventDefault();
        if (this.state.email.search(
            /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/) === -1) {
            this.setState({errorMsg: 'E-mail inválido'});
        } else {
            axios.post('/register', {email: this.state.email, password: this.state.password})
            .then(res => {
                this.setState({email: res.data.email, emailConfirm: true, errorMsg: ''});
            }).catch(err => {
                if (err.response.status === 409) {
                    this.setState({errorMsg: 'Já existe um usuário cadastrado com o e-mail informado'});
                } else {
                    this.setState({errorMsg: err.response.statusText});
                }
            })
        }
    };


    render() {
        return (
            <div className='login-sing-in-container'>
                {this.state.emailConfirm === false ?
                    <form className="register-form">
                        <h1>Cadastro</h1>

                        {this.state.errorMsg !== '' ? <ErrorMessage message={this.state.errorMsg}/> : null}
                        <InputField label='E-mail' name='email' onChange={this.handleChange} type='email'/>
                        <InputField label='Senha' name='password' onChange={this.handleChange} type='password'/>

                        <RoundButton label='Cadastrar' onClick={this.handleSubmit} type='submit'/>
                    </form> :
                    <div className='confirmWindow'>
                        <h1>Confirme o email</h1>
                        <p>Enviamos um email de confirmação de cadastro para <b>{this.state.email}</b>,
                        <br/>para ativar sua conta por favor siga as instruções informadas no email</p>
                        <div>
                            <RoundButton label='Confirmar e-mail'/> {/*função ainda precissa ser implementado*/}
                        </div>
                    </div>
                }
            </div>
        )
    }
}
